<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Joaquin Ramirez">

<title>Joaquin Ramirez - Time Series</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Joaquin Ramirez</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../aboutme.html" rel="" target="">
 <span class="menu-text">About Me</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-projects" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Projects</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-projects">    
        <li>
    <a class="dropdown-item" href="../starter-analysis-exercise/products/report/starter-analysis-report.html" rel="" target="">
 <span class="dropdown-text">Starter Analysis Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../coding-exercise/coding-exercise.html" rel="" target="">
 <span class="dropdown-text">R Coding Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../presentation-exercise/presentation-exercise.html" rel="" target="">
 <span class="dropdown-text">Presentation Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../tidytuesday-exercise/tidytuesday-exercise.html" rel="" target="">
 <span class="dropdown-text">Tidy Tuesday Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../data-exercise/data-exercise.html" rel="" target="">
 <span class="dropdown-text">Data Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../cdcdata-exercise/cdcdata-exercise.html" rel="" target="">
 <span class="dropdown-text">CDC Data Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../time-series/practicum1.html" rel="" target="">
 <span class="dropdown-text">Time Series</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../market-segmentation/market-segmentation.html" rel="" target="">
 <span class="dropdown-text">Market Segmentation: Dr Pepper</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../predictive-modeling/predictive-modeling.html" rel="" target="">
 <span class="dropdown-text">Predictive Modeling</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/Jramirez1995/Joaquin_Ramriez_Portfolio_II.git" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Time Series</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Joaquin Ramirez </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<p>In the field of data analysis, a robust understanding of statistical concepts is essential for accurate and insightful interpretation of data. This section provides a comprehensive overview of fundamental statistical principles and methodologies applied during my practicum in the UTSA Master’s program in Data Analytics. The emphasis is on leveraging these principles to analyze diverse datasets using advanced statistical software and tools, including R Studio, GRETL, Python, and SAS Enterprise.</p>
<p>The report begins with an exploration of time series analysis, followed by an examination of the Durbin-Watson statistic, and then proceeds with ARIMA modeling. It also includes examples of code used in SAS 94 New Cluster and concludes with a discussion of key statistical concepts.</p>
<p>Various techniques were employed, such as Autocorrelation Function (ACF) plots and formal statistical tests including the KPSS and Augmented Dickey-Fuller (ADF) tests.</p>
<section id="time-series-analysis-wind-speed-in-delhi" class="level1">
<h1>Time Series Analysis: <strong>Wind Speed in Delhi</strong></h1>
<p><strong>Introduction</strong>: The goal of this section is to analyze time series datasets by investigating whether their mean remains constant over time. This analysis involves importing time series data into <a href="http://gretl.sourceforge.net/"><strong>GRETL</strong></a> , visualizing the data, and applying statistical tests to determine whether the time series exhibits a constant mean. The methods used include visual inspection through plotting and formal statistical testing via the KPSS and Augmented Dickey-Fuller (ADF) tests.</p>
<p>Dataset: <a href="https://www.kaggle.com/datasets/sumanthvrao/daily-climate-time-series-data"><strong>Wind Speed in Delhi</strong></a> The first dataset selected for analysis records wind speed (measured in km/h) in Delhi, India, from January 1, 2013, to April 24, 2017.</p>
<p>To begin the analysis, the wind speed data was plotted over time. By visually inspecting the plot, it appeared that the mean wind speed remained relatively constant throughout the time period. However, a subtle trend was observable in certain segments of the data, which warranted further investigation.</p>
<p><img src="Plot1.png" class="img-fluid"></p>
<p>An autocorrelation function (ACF) plot was generated to assess the presence of autocorrelation and trends. The ACF plot exhibited a slight decrease in correlation as the lag increased, indicating autocorrelation in the dataset. This trend suggested that the mean might not be perfectly constant across the entire time series.</p>
<p><img src="Picture2.png" class="img-fluid"></p>
<p>To formally test for a constant mean, two statistical tests were applied to the dataset:</p>
<ol type="1">
<li><strong>KPSS Test</strong>: The null hypothesis (Ho) of the KPSS test states that the mean is constant over time. The test statistic for the wind speed dataset was 0.216261, and with a p-value greater than 0.10, we failed to reject the null hypothesis. Thus, the KPSS test suggested that the mean wind speed is constant over time.</li>
</ol>
<pre><code>T = 1462

Lag truncation parameter = 7

Test statistic = 0.216261

10%&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5%&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1%

Critical values: 0.348&nbsp;&nbsp; 0.462&nbsp;&nbsp; 0.743

P-value \&gt; .10</code></pre>
<ol start="2" type="1">
<li><strong>Augmented Dickey-Fuller (ADF) Test:</strong> The ADF test’s null hypothesis (Ho) posits that the series has a unit root, implying a non-constant mean. The test statistic for the wind speed data was -4.11449, with a p-value of 0.0009163. This result led to the rejection of the null hypothesis, indicating that the mean wind speed was likely constant over time.</li>
</ol>
<pre><code>    Augmented Dickey-Fuller test for wind_speed

    testing down from 23 lags, criterion AIC

    sample size 1438

    unit-root null hypothesis: a = 1

    test with constant

    including 23 lags of (1-L)wind_speed

    model: (1-L)y = b0 + (a-1)\*y(-1) + \... + e

    estimated value of (a - 1): -0.211152

    test statistic: tau_c(1) = -4.11449

    asymptotic p-value 0.0009163

    1st-order autocorrelation coeff. for e: -0.003

    lagged differences: F(23, 1413) = 3.597 \[0.0000\]</code></pre>
<p>In conclusion, this analysis applied visual inspection, ACF plots, and statistical tests to assess whether the mean of two time series datasets remained constant over time. The results varied across datasets. For the wind speed data, both visual inspection and statistical testing suggested a constant mean over time. In the case of Microsoft stock volume, the KPSS test indicated a non-constant mean, while the ADF test suggested otherwise, pointing to the importance of using multiple tests in time series analysis. This report demonstrates how combining visual methods with formal statistical testing can provide a robust understanding of the characteristics of time series data.</p>
</section>
<section id="time-series-analysis-microsoft-stock" class="level1">
<h1>Time Series Analysis: Microsoft Stock</h1>
<p>Dataset 2: <a href="https://www.kaggle.com/datasets/vijayvvenkitesh/microsoft-stock-time-series-analysis"><strong>Microsoft Stock- Time Series Analysis</strong></a></p>
<p>This analysis focuses on the stock trading volume for Microsoft from April 1, 2015, to April 1, 2021. The objective was to examine the behavior of the stock volume over time and determine whether its mean remained constant.</p>
<p>The initial visual inspection of the Microsoft stock trading volume plot indicated that the mean volume appeared relatively stable throughout the observation period. There were no noticeable upward or downward trends in the data.</p>
<p><img src="marget-segmentation/Picture3.png" class="img-fluid"></p>
<p>To gain a deeper understanding, we analyzed the autocorrelation function (ACF) plot. The ACF plot demonstrated a gradual decline in autocorrelation as the lag increased, suggesting some level of autocorrelation in the dataset. However, this plot alone did not provide a clear indication of a trend or non-constant mean.</p>
<p><img src="marget-segmentation/Picture4.png" class="img-fluid" width="667"></p>
<p>To gain a more rigorous understanding of whether the mean stock trading volume remained constant over time, we employed two key statistical tests:</p>
<p><strong>KPSS Test</strong>: For the stock volume data, the KPSS test yielded a test statistic of 0.646783 and a p-value of 0.024. Given that the p-value is below the significance threshold of 0.05, we reject the null hypothesis. This result indicates that the mean stock volume is not constant over the observed period.</p>
<pre><code>T = 1511

Lag truncation parameter = 7

Test statistic = 0.646783

10%&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5%&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1%

Critical values: 0.348&nbsp;&nbsp; 0.462&nbsp;&nbsp; 0.743

Interpolated p-value 0.024</code></pre>
<p>Following the KPSS test, we also applied the Augmented Dickey-Fuller (ADF) test to further investigate the stability of the stock trading volume:</p>
<p><strong>Augmented Dickey-Fuller (ADF) Test</strong>: The ADF test produced a test statistic of -6.89966 and a p-value of 6.158e-10. Since the p-value is significantly below the significance level, we reject the null hypothesis of a non-constant mean. This result supports the conclusion that the mean trading volume was indeed constant over the observed period.</p>
<pre><code>Augmented Dickey-Fuller test for Volume

testing down from 23 lags, criterion AIC

sample size 1502

unit-root null hypothesis: a = 1

test with constant

including 8 lags of (1-L)Volume

model: (1-L)y = b0 + (a-1)\*y(-1) + \... + e

estimated value of (a - 1): -0.185615

test statistic: tau_c(1) = -6.89966

asymptotic p-value 6.158e-10

1st-order autocorrelation coeff. for e: -0.001

lagged differences: F(8, 1492) = 13.263 \[0.0000\]</code></pre>
<p>In conclusion this analysis applied visual inspection, ACF plots, and statistical tests to assess whether the mean of two time series datasets remained constant over time. The results varied across datasets. For the wind speed data, both visual inspection and statistical testing suggested a constant mean over time. In the case of Microsoft stock volume, the KPSS test indicated a non-constant mean, while the ADF test suggested otherwise, pointing to the importance of using multiple tests in time series analysis. This report demonstrates how combining visual methods with formal statistical testing can provide a robust understanding of the characteristics of time series data.</p>
</section>
<section id="time-series-data-analysis-report-2-forecasting-from-gold-price" class="level1">
<h1>Time Series Data Analysis Report 2: Forecasting from Gold Price</h1>
<p><strong>Objective:</strong></p>
<p>The aim of this analysis is to apply time series forecasting techniques to historical gold price data. By employing various statistical tests and models, we seek to predict future gold prices and assess the stationarity of the dataset.</p>
<p><strong>Introduction:</strong></p>
<p>Gold has long been a valuable commodity, widely used in jewelry and as an investment asset. Prices for gold fluctuate daily due to a variety of economic factors and are actively traded on global commodity exchanges. This project uses historical gold price data to forecast future prices, applying time series forecasting methods to gain insights into market trends.</p>
<p><strong>Dataset:</strong></p>
<p>For this analysis, we utilized a dataset from Quandl, which provides extensive financial and economic data. This dataset includes daily gold prices spanning several decades, beginning in the 1970s. You can access the dataset here: <a href="https://www.kaggle.com/datasets/arashnic/learn-time-series-forecasting-from-gold-price"><strong>Gold Price Time Series</strong></a></p>
<p><strong>Data Visualization:</strong></p>
<p>The first step in our analysis involved plotting the raw time series data of gold prices. The resulting plot shows significant fluctuations over time, suggesting a non-constant mean and variance. These visual indications imply that the time series may be non-stationary.</p>
<p><img src="Picture10.png" class="img-fluid"></p>
<p>To further investigate, we examined the Autocorrelation Function (ACF) and Partial Autocorrelation Function (PACF) to better understand the underlying characteristics of the time series. The ACF plot suggest that no consistent pattern across the data, suggesting a non-constant mean. The lack of clear trends in the ACF supports our earlier conclusion of non-stationarity.<br>
<img src="Picture11.png" class="img-fluid"></p>
<p>To confirm the stationarity of the dataset, we conducted two statistical tests, the KPSS test and the Augmented Dickey-Fuller (ADF) test.</p>
<ol type="1">
<li><strong>KPSS test for Value:</strong></li>
</ol>
<pre><code>T = 10787

Lag truncation parameter = 12

Test statistic = 55.3031

10%&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5%&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1%

Critical values: 0.347&nbsp;&nbsp; 0.462&nbsp;&nbsp; 0.744

P-value \&lt; .01</code></pre>
<p><strong>H<sub>0</sub>:</strong>&nbsp; no evidence data has more than one mean (fits stationary criteria)</p>
<p><strong>Ha:</strong> data has more than one mean (e.g.&nbsp;non-stationary)</p>
<p>Because p &lt; .05, we reject H<sub>0</sub> and so there is evidence of more than one mean. (It is non-stationary)</p>
<ol start="2" type="1">
<li><strong>Augmented Dickey-Fuller test for Value</strong></li>
</ol>
<pre><code>testing down from 38 lags, criterion AIC

sample size 10754

unit-root null hypothesis: a = 1

test with constant

including 32 lags of (1-L)Value

model: (1-L)y = b0 + (a-1)\*y(-1) + \... + e

estimated value of (a - 1): -3.11791e-005

test statistic: tau_c(1) = -0.155837

asymptotic p-value 0.9415

1st-order autocorrelation coeff. for e: 0.000

lagged differences: F(32, 10720) = 4.775 \[0.0000\]</code></pre>
<p><strong>H<sub>0</sub>:</strong> data has more than one mean (e.g.&nbsp;non-stationary)</p>
<p><strong>Ha</strong>: data has one mean (e.g.&nbsp;stationary)</p>
<p>Since the p-value is greater than 0.05, we do not reject the null hypothesis, which suggests that the data is non-stationary. Both tests confirm that the gold price dataset exhibits non-stationarity.</p>
<p>To address this, we applied differencing to the time series to remove the trend and stabilize the mean. The plot of the differenced data is shown below:</p>
<p><img src="Picture12.png" class="img-fluid"></p>
<p>After differencing, the data appears more stationary, with the trend and non-constant mean effectively removed. The ACF and PACF plots further indicate that differencing was successful in stabilizing the series, suggesting that the data is now stationary.</p>
<p><img src="Picture13.png" class="img-fluid"></p>
<p>To validate the stationarity of the differenced data, we applied the KPSS and ADF tests again.</p>
<ol type="1">
<li><strong>KPSS Test Results on Differenced Data</strong></li>
</ol>
<pre><code>T = 10786

Lag truncation parameter = 12

Test statistic = 0.136227

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 10%&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5%&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1%

Critical values: 0.347&nbsp;&nbsp; 0.462&nbsp;&nbsp; 0.744

P-value \&gt; .10</code></pre>
<p>H<sub>0</sub>:&nbsp; no evidence data has more than one mean (fits stationary criteria)</p>
<p>Ha: data has more than one mean (e.g.&nbsp;non-stationary)</p>
<p>Since the p-value is greater than 0.05, we fail to reject the null hypothesis, indicating that the differenced data is stationary.</p>
<ol start="2" type="1">
<li><strong>Augmented Dickey-Fuller test for Differenced Data</strong></li>
</ol>
<pre><code>testing down from 38 lags, criterion AIC

sample size 10747

unit-root null hypothesis: a = 1

test with constant

including 38 lags of (1-L)d_Value

model: (1-L)y = b0 + (a-1)\*y(-1) + \... + e

estimated value of (a - 1): -1.11688

test statistic: tau_c(1) = -17.5688

asymptotic p-value 3.402e-42

1st-order autocorrelation coeff. for e: 0.000

lagged differences: F(38, 10707) = 4.529 \[0.0000\]</code></pre>
<p><strong>H<sub>0</sub>:</strong> data has more than one mean (e.g.&nbsp;non-stationary)</p>
<p><strong>Ha:</strong> data has one mean (e.g.&nbsp;stationary)</p>
<p>Given the extremely low p-values from both the KPSS and ADF tests, we reject the null hypothesis (H₀). This confirms that the differenced data is stationary. Consequently, we will proceed with the differenced time series data for further analysis.</p>
<p>Next, we examined the Autocorrelation Function (ACF) and Partial Autocorrelation Function (PACF) plots to assess the presence of autoregressive (AR) and moving average (MA) processes. The ACF and PACF plots revealed both negative and positive lags in the data, indicating the presence of autoregressive and moving average components.</p>
<p><strong>Additional Resources: <a href="https://people.duke.edu/~rnau/411arim3.htm">Duke University</a></strong> &amp; <a href="#0"><strong>Penn State</strong></a></p>
<p><img src="Picture7.png" class="img-fluid"></p>
<p>We then experimented with various ARIMA models and evaluated their performance based on several metrics. The results are summarized in the table below:</p>
<table class="table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th>Adjusted R-squared</th>
<th>AIC</th>
<th>BIC (Schwartz)</th>
<th>Hannan-Quinn</th>
<th>Ljung-Box</th>
<th>ARCH p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(1,0,1)</td>
<td>0.0002</td>
<td>78091.04</td>
<td>78120.19</td>
<td>78100.87</td>
<td>0.001281</td>
<td>6.90E-211</td>
</tr>
<tr class="even">
<td>(2,0,1)</td>
<td>0.0016</td>
<td>78081.13</td>
<td>78117.56</td>
<td>78093.41</td>
<td>0.02874</td>
<td>2.30E-209</td>
</tr>
<tr class="odd">
<td>(1,0,2)</td>
<td>0.001205</td>
<td>78081.19</td>
<td>78117.62</td>
<td>78093.48</td>
<td>0.02738</td>
<td>2.39E-209</td>
</tr>
<tr class="even">
<td>(1,0,3)</td>
<td>0.001158</td>
<td>78082.70</td>
<td>78097.45</td>
<td>78126.42</td>
<td>0.09325</td>
<td>1.36E-207</td>
</tr>
<tr class="odd">
<td>(2,0,2)</td>
<td>0.004335</td>
<td>78048.39</td>
<td>78092.11</td>
<td>78063.13</td>
<td>0.1218</td>
<td>1.96E-201</td>
</tr>
</tbody>
</table>
<p>After reviewing the performance metrics, I selected the (2,0,2) model as the best fit for the data. This model has the highest adjusted R-squared value and the lowest AIC and BIC values, indicating better overall model fit.</p>
<p>We plotted the observed versus fitted data for the selected time series models to evaluate their performance:</p>
<p><img src="Picture8.png" class="img-fluid"></p>
<p>Using the selected (2,0,2) model, we forecasted gold prices for six periods ahead. The forecast aligns well with historical data, although further validation over a longer horizon is recommended.</p>
<p><img src="Picture9.png" class="img-fluid" width="643"></p>
<p><strong>Variance Testing</strong>:</p>
<p>The ARCH test results indicate significant non-constant variance in the selected model. Despite this, no immediate corrective measures are planned.</p>
<table class="table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th>Adjusted R-squared</th>
<th>AIC</th>
<th>BIC (Schwartz)</th>
<th>Hannan-Quinn</th>
<th>Ljung-Box</th>
<th>ARCH p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(1,0,1)</td>
<td>0.0002</td>
<td>78091.04</td>
<td>78120.19</td>
<td>78100.87</td>
<td>0.001281</td>
<td>6.90E-211</td>
</tr>
<tr class="even">
<td>(2,0,1)</td>
<td>0.0016</td>
<td>78081.13</td>
<td>78117.56</td>
<td>78093.41</td>
<td>0.02874</td>
<td>2.30E-209</td>
</tr>
<tr class="odd">
<td>(1,0,2)</td>
<td>0.001205</td>
<td>78081.19</td>
<td>78117.62</td>
<td>78093.48</td>
<td>0.02738</td>
<td>2.39E-209</td>
</tr>
<tr class="even">
<td>(1,0,3)</td>
<td>0.001158</td>
<td>78082.70</td>
<td>78097.45</td>
<td>78126.42</td>
<td>0.09325</td>
<td>1.36E-207</td>
</tr>
<tr class="odd">
<td>(2,0,2)</td>
<td>0.004335</td>
<td>78048.39</td>
<td>78092.11</td>
<td>78063.13</td>
<td>0.1218</td>
<td>1.96E-201</td>
</tr>
</tbody>
</table>
<p>Overall, the analysis confirms the stationarity of the differenced gold price data and identifies the (2,0,2) ARIMA model as the most suitable for forecasting, despite some issues with variance constancy.</p>
</section>
<section id="durbin-watson-test-on-time-series-data" class="level1">
<h1>Durbin Watson Test on Time Series Data</h1>
<p><strong>Introduction:</strong></p>
<p>This report presents the application of the Durbin-Watson test to detect autocorrelation in time series data, specifically using multiple regression on retail datasets. The objective is to determine whether the regression residuals display autocorrelation, which would violate a key assumption of linear regression: that the error terms are independent.</p>
<p>Autocorrelation in residuals can lead to biased and inefficient estimates of regression coefficients, as well as incorrect inferences, such as inflated t-statistics and misleading confidence intervals. The Durbin-Watson test statistic is employed to assess the presence of autocorrelation.</p>
<p><strong>Time Series Examination of Retail 1</strong></p>
<p><img src="Picture100.png" class="img-fluid" width="639"></p>
<p><img src="Picture101.png" class="img-fluid" width="638"></p>
<p>Initial visual inspection of the Retail 1 data, using the “Mark I Eyeball” method, indicates a constant mean with no significant trend. This observation is promising for the assumption of uncorrelated error terms.</p>
<p>Further analysis with the autocorrelation function (ACF) plot shows some minor autocorrelation but not severe enough to cause major concerns.</p>
<p><strong>Durbin-Watson Test Results for Retail 1:</strong></p>
<p>For a sample size of <strong>T = 49</strong>, the Durbin-Watson test boundaries at <strong>α = 0.05</strong> are:</p>
<ul>
<li><p><strong>Lower Bound (DL):</strong> 1.141</p></li>
<li><p><strong>Upper Bound (DU):</strong> 1.499</p></li>
</ul>
<p>To further investigate, I ran an Ordinary Least Squares (OLS) regression on the Retail 1 data using GRETL. Below are the key metrics from the regression:</p>
<table class="table">
<colgroup>
<col style="width: 48%">
<col style="width: 51%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Metric</strong></th>
<th><strong>Value</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Model</strong></td>
<td>High-Precision OLS, using observations (T = 49)</td>
</tr>
<tr class="even">
<td><strong>Dependent Variable</strong></td>
<td>Sales</td>
</tr>
<tr class="odd">
<td><strong>Coefficient (const)</strong></td>
<td>1.2226 x 10^4</td>
</tr>
<tr class="even">
<td><strong>Std. Error (const)</strong></td>
<td>829.31</td>
</tr>
<tr class="odd">
<td><strong>Mean Dependent Var</strong></td>
<td>1.2226 x 10^4</td>
</tr>
<tr class="even">
<td><strong>S.D. Dependent Var</strong></td>
<td>5.8052 x 10^3</td>
</tr>
<tr class="odd">
<td><strong>Sum Squared Resid</strong></td>
<td>1.6176 x 10^9</td>
</tr>
<tr class="even">
<td><strong>S.E. of Regression</strong></td>
<td>5.8052 x 10^3</td>
</tr>
<tr class="odd">
<td><strong>R-squared</strong></td>
<td>-5.1817 x 10^-77</td>
</tr>
<tr class="even">
<td><strong>Adjusted R-squared</strong></td>
<td>-5.1817 x 10^-77</td>
</tr>
<tr class="odd">
<td><strong>F(1, 48)</strong></td>
<td>217.34</td>
</tr>
<tr class="even">
<td><strong>P-value(F)</strong></td>
<td>1.9018 x 10^-19</td>
</tr>
<tr class="odd">
<td><strong>Log-Likelihood</strong></td>
<td>-493.68</td>
</tr>
<tr class="even">
<td><strong>Akaike Criterion</strong></td>
<td>989.36</td>
</tr>
<tr class="odd">
<td><strong>Schwarz Criterion</strong></td>
<td>991.26</td>
</tr>
<tr class="even">
<td><strong>Hannan-Quinn</strong></td>
<td>990.08</td>
</tr>
<tr class="odd">
<td><strong>Rho</strong></td>
<td>-0.0302</td>
</tr>
<tr class="even">
<td><strong>Durbin-Watson</strong></td>
<td>2.049</td>
</tr>
</tbody>
</table>
<p>The Durbin-Watson statistic of 2.049 exceeds the upper bound (DU), indicating no significant autocorrelation. Thus, the residuals of Retail 1 do not exhibit significant autocorrelation, validating the regression results under the assumption of independent errors.</p>
<p><strong>Time Series Examination of Retail 2 Dataset</strong></p>
<p>For Retail 2, visual inspection also shows a constant mean and no significant trend. The ACF plot indicates minor autocorrelation, but it is not severe enough to challenge the assumption of uncorrelated error terms.</p>
<p><img src="Picture102.png" class="img-fluid"></p>
<p><img src="Picture103.png" class="img-fluid"></p>
<p><strong>Durbin-Watson Test Results for Retail 2:</strong></p>
<p>For a sample size of <strong>T = 39</strong>, the Durbin-Watson test boundaries at <strong>α = 0.05</strong> are:</p>
<ul>
<li><p><strong>Lower Bound (DL):</strong> 1.376</p></li>
<li><p><strong>Upper Bound (DU):</strong> 1.604</p></li>
</ul>
<p>Running an OLS regression on the Retail 2 data in GRETL provides the following results:</p>
<table class="table">
<colgroup>
<col style="width: 48%">
<col style="width: 51%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Metric</strong></th>
<th><strong>Value</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Model</strong></td>
<td>High-Precision OLS, using observations 2011-03-15:2011-04-22 (T = 39)</td>
</tr>
<tr class="even">
<td><strong>Dependent Variable</strong></td>
<td>Sales</td>
</tr>
<tr class="odd">
<td><strong>Coefficient (const)</strong></td>
<td>1.2849 x 10^4</td>
</tr>
<tr class="even">
<td><strong>Std. Error (const)</strong></td>
<td>901.07</td>
</tr>
<tr class="odd">
<td><strong>Mean Dependent Var</strong></td>
<td>1.2849 x 10^4</td>
</tr>
<tr class="even">
<td><strong>S.D. Dependent Var</strong></td>
<td>5.6272 x 10^3</td>
</tr>
<tr class="odd">
<td><strong>Sum Squared Resid</strong></td>
<td>1.2033 x 10^9</td>
</tr>
<tr class="even">
<td><strong>S.E. of Regression</strong></td>
<td>5.6272 x 10^3</td>
</tr>
<tr class="odd">
<td><strong>R-squared</strong></td>
<td>-6.9089 x 10^-77</td>
</tr>
<tr class="even">
<td><strong>Adjusted R-squared</strong></td>
<td>-6.9089 x 10^-77</td>
</tr>
<tr class="odd">
<td><strong>F(1, 38)</strong></td>
<td>203.35</td>
</tr>
<tr class="even">
<td><strong>P-value(F)</strong></td>
<td>7.7600 x 10^-17</td>
</tr>
<tr class="odd">
<td><strong>Log-Likelihood</strong></td>
<td>-391.61</td>
</tr>
<tr class="even">
<td><strong>Akaike Criterion</strong></td>
<td>785.22</td>
</tr>
<tr class="odd">
<td><strong>Schwarz Criterion</strong></td>
<td>786.89</td>
</tr>
<tr class="even">
<td><strong>Hannan-Quinn</strong></td>
<td>785.82</td>
</tr>
<tr class="odd">
<td><strong>Rho</strong></td>
<td>0.1236</td>
</tr>
<tr class="even">
<td><strong>Durbin-Watson</strong></td>
<td>1.737</td>
</tr>
</tbody>
</table>
<p>The Durbin-Watson statistic of 1.737 is between the lower bound (DL) and upper bound (DU), indicating no significant autocorrelation. Thus, the residuals of Retail 2 also do not exhibit significant autocorrelation, validating the regression results under the assumption of independent errors.</p>
<p><strong>Summary:</strong></p>
<p>The Durbin-Watson test results for both Retail 1 and Retail 2 datasets suggest that autocorrelation is not a significant issue. The residuals in the regression models are uncorrelated, which supports the validity of the regression results. The assumption of independent errors is upheld, ensuring the reliability of the models used.</p>
</section>
<section id="arima-model-comparison" class="level1">
<h1>ARIMA Model Comparison</h1>
<p>This report analyzes the unemployment rate in the US from January 1948 to March 2020. The analysis involves plotting the time series data, differencing to achieve stationarity, and fitting various ARIMA models to the differenced data. The models are evaluated using several metrics, including AIC, BIC, and the Ljung-Box test.</p>
<p><strong>Time Series Plot:</strong> The plot below shows the unemployment rate from January 1948 to March 2020.</p>
<p><img src="Picture5.png" class="img-fluid"></p>
<p><strong>Differenced Data Plot:</strong> The first differenced data is used to achieve stationarity, as illustrated in the plot below.</p>
<p><img src="Picture26.png" class="img-fluid"></p>
<p>________________________________________________________________________________________</p>
<p>ARIMA Model Analysis</p>
<p><strong>Model 1: ARMA(1,1)</strong></p>
<ul>
<li><p><strong>Observations:</strong> 1948:02-2020:03 (T = 866)</p></li>
<li><p><strong>Dependent Variable:</strong> d_UNRATE</p></li>
<li><p><strong>Standard Errors:</strong> Based on Hessian</p></li>
</ul>
<table class="table">
<colgroup>
<col style="width: 18%">
<col style="width: 15%">
<col style="width: 17%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Coefficient</th>
<th>Estimate</th>
<th>Std. Error</th>
<th>z-value</th>
<th>p-value</th>
<th>Significance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>const</td>
<td>0.002873</td>
<td>0.014791</td>
<td>0.1942</td>
<td>0.8460</td>
<td></td>
</tr>
<tr class="even">
<td>phi_1</td>
<td>0.870665</td>
<td>0.029667</td>
<td>29.3500</td>
<td>&lt;0.0001</td>
<td>***</td>
</tr>
<tr class="odd">
<td>theta_1</td>
<td>-0.718031</td>
<td>0.037947</td>
<td>-18.9200</td>
<td>&lt;0.0001</td>
<td>***</td>
</tr>
</tbody>
</table>
<p><strong>Model Fit Statistics:</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>Statistic</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mean dependent var</td>
<td>0.001155</td>
</tr>
<tr class="even">
<td>S.D. dependent var</td>
<td>0.209924</td>
</tr>
<tr class="odd">
<td>Mean of innovations</td>
<td>-0.000378</td>
</tr>
<tr class="even">
<td>S.D. of innovations</td>
<td>0.200521</td>
</tr>
<tr class="odd">
<td>R-squared</td>
<td>0.086522</td>
</tr>
<tr class="even">
<td>Adjusted R-squared</td>
<td>0.085465</td>
</tr>
<tr class="odd">
<td>Log-likelihood</td>
<td>162.6270</td>
</tr>
<tr class="even">
<td>Akaike criterion</td>
<td>-317.2540</td>
</tr>
<tr class="odd">
<td>Schwarz criterion</td>
<td>-298.1985</td>
</tr>
<tr class="even">
<td>Hannan-Quinn</td>
<td>-309.9612</td>
</tr>
</tbody>
</table>
<p><strong>Roots of AR and MA Polynomials:</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>Type</th>
<th>Root</th>
<th>Real</th>
<th>Imaginary</th>
<th>Modulus</th>
<th>Frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>AR</td>
<td>Root 1</td>
<td>1.1485</td>
<td>0.0000</td>
<td>1.1485</td>
<td>0.0000</td>
</tr>
<tr class="even">
<td>MA</td>
<td>Root 1</td>
<td>1.3927</td>
<td>0.0000</td>
<td>1.3927</td>
<td>0.0000</td>
</tr>
</tbody>
</table>
<p>________________________________________________________________________________________</p>
<p><strong>Autocorrelation Test:</strong></p>
<ul>
<li><p><strong>Ljung-Box Q’</strong> = 75.3636</p></li>
<li><p><strong>p-value</strong> = 4.042e-012</p></li>
</ul>
<p><strong>Model 2: ARMA(2,1)</strong></p>
<ul>
<li><p><strong>Observations:</strong> 1948:02-2020:03 (T = 866)</p></li>
<li><p><strong>Dependent Variable:</strong> d_UNRATE</p></li>
<li><p><strong>Standard Errors:</strong> Based on Hessian</p></li>
</ul>
<table class="table">
<colgroup>
<col style="width: 18%">
<col style="width: 15%">
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Coefficient</th>
<th>Estimate</th>
<th>Std. Error</th>
<th>z-value</th>
<th>p-value</th>
<th>Significance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>const</td>
<td>0.002986</td>
<td>0.014898</td>
<td>0.2004</td>
<td>0.8412</td>
<td></td>
</tr>
<tr class="even">
<td>phi_1</td>
<td>0.555245</td>
<td>0.062518</td>
<td>8.881</td>
<td>&lt;0.0001</td>
<td>***</td>
</tr>
<tr class="odd">
<td>phi_2</td>
<td>0.238727</td>
<td>0.037380</td>
<td>6.386</td>
<td>&lt;0.0001</td>
<td>***</td>
</tr>
<tr class="even">
<td>theta_1</td>
<td>-0.538385</td>
<td>0.058356</td>
<td>-9.226</td>
<td>&lt;0.0001</td>
<td>***</td>
</tr>
</tbody>
</table>
<p><strong>Model Fit Statistics:</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>Statistic</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mean dependent var</td>
<td>0.001155</td>
</tr>
<tr class="even">
<td>S.D. dependent var</td>
<td>0.209924</td>
</tr>
<tr class="odd">
<td>Mean of innovations</td>
<td>-0.000420</td>
</tr>
<tr class="even">
<td>S.D. of innovations</td>
<td>0.196462</td>
</tr>
<tr class="odd">
<td>R-squared</td>
<td>0.123133</td>
</tr>
<tr class="even">
<td>Adjusted R-squared</td>
<td>0.121101</td>
</tr>
<tr class="odd">
<td>Log-likelihood</td>
<td>180.2785</td>
</tr>
<tr class="even">
<td>Akaike criterion</td>
<td>-350.5570</td>
</tr>
<tr class="odd">
<td>Schwarz criterion</td>
<td>-326.7375</td>
</tr>
<tr class="even">
<td>Hannan-Quinn</td>
<td>-341.4410</td>
</tr>
</tbody>
</table>
<p><strong>Roots of AR and MA Polynomials:</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>Type</th>
<th>Root</th>
<th>Real</th>
<th>Imaginary</th>
<th>Modulus</th>
<th>Frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>AR</td>
<td>Root 1</td>
<td>1.1911</td>
<td>0.0000</td>
<td>1.1911</td>
<td>0.0000</td>
</tr>
<tr class="even">
<td>AR</td>
<td>Root 2</td>
<td>-3.5169</td>
<td>0.0000</td>
<td>3.5169</td>
<td>0.5000</td>
</tr>
<tr class="odd">
<td>MA</td>
<td>Root 1</td>
<td>1.8574</td>
<td>0.0000</td>
<td>1.8574</td>
<td>0.0000</td>
</tr>
</tbody>
</table>
<p>________________________________________________________________________________________</p>
<p><strong>Autocorrelation Test:</strong></p>
<ul>
<li><p><strong>Ljung-Box Q’</strong> = 36.8101</p></li>
<li><p><strong>p-value</strong> = 2.845e-005</p></li>
</ul>
<p><strong>Model 3: ARMA(2,2)</strong></p>
<ul>
<li><p><strong>Observations:</strong> 1948:02-2020:03 (T = 866)</p></li>
<li><p><strong>Dependent Variable:</strong> d_UNRATE</p></li>
<li><p><strong>Standard Errors:</strong> Based on Hessian</p></li>
</ul>
<table class="table">
<colgroup>
<col style="width: 18%">
<col style="width: 15%">
<col style="width: 17%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Coefficient</th>
<th>Estimate</th>
<th>Std. Error</th>
<th>z-value</th>
<th>p-value</th>
<th>Significance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>const</td>
<td>0.002579</td>
<td>0.011520</td>
<td>0.2239</td>
<td>0.8228</td>
<td></td>
</tr>
<tr class="even">
<td>phi_1</td>
<td>1.655610</td>
<td>0.037484</td>
<td>44.1700</td>
<td>&lt;0.0001</td>
<td>***</td>
</tr>
<tr class="odd">
<td>phi_2</td>
<td>-0.782771</td>
<td>0.043359</td>
<td>-18.0500</td>
<td>&lt;0.0001</td>
<td>***</td>
</tr>
<tr class="even">
<td>theta_1</td>
<td>-1.641770</td>
<td>0.038375</td>
<td>-42.7800</td>
<td>&lt;0.0001</td>
<td>***</td>
</tr>
<tr class="odd">
<td>theta_2</td>
<td>0.863215</td>
<td>0.047917</td>
<td>18.0100</td>
<td>&lt;0.0001</td>
<td>***</td>
</tr>
</tbody>
</table>
<p><strong>Model Fit Statistics:</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>Statistic</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mean dependent var</td>
<td>0.001155</td>
</tr>
<tr class="even">
<td>S.D. dependent var</td>
<td>0.209924</td>
</tr>
<tr class="odd">
<td>Mean of innovations</td>
<td>-0.000443</td>
</tr>
<tr class="even">
<td>S.D. of innovations</td>
<td>0.194870</td>
</tr>
<tr class="odd">
<td>R-squared</td>
<td>0.137289</td>
</tr>
<tr class="even">
<td>Adjusted R-squared</td>
<td>0.134286</td>
</tr>
<tr class="odd">
<td>Log-likelihood</td>
<td>187.0535</td>
</tr>
<tr class="even">
<td>Akaike criterion</td>
<td>-362.1069</td>
</tr>
<tr class="odd">
<td>Schwarz criterion</td>
<td>-333.5236</td>
</tr>
<tr class="even">
<td>Hannan-Quinn</td>
<td>-351.1678</td>
</tr>
</tbody>
</table>
<p><strong>Roots of AR and MA Polynomials:</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>Type</th>
<th>Root</th>
<th>Real</th>
<th>Imaginary</th>
<th>Modulus</th>
<th>Frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>AR</td>
<td>Root 1</td>
<td>1.0575</td>
<td>-0.3989</td>
<td>1.1303</td>
<td>-0.0574</td>
</tr>
<tr class="even">
<td>AR</td>
<td>Root 2</td>
<td>1.0575</td>
<td>0.3989</td>
<td>1.1303</td>
<td>0.0574</td>
</tr>
<tr class="odd">
<td>MA</td>
<td>Root 1</td>
<td>0.9510</td>
<td>-0.5041</td>
<td>1.0763</td>
<td>-0.0776</td>
</tr>
<tr class="even">
<td>MA</td>
<td>Root 2</td>
<td>0.9510</td>
<td>0.5041</td>
<td>1.0763</td>
<td>0.0776</td>
</tr>
</tbody>
</table>
<p>________________________________________________________________________________________</p>
<p><strong>Autocorrelation Test:</strong></p>
<ul>
<li><p><strong>Ljung-Box Q’</strong> = 39.2977</p></li>
<li><p><strong>p-value</strong> = 4.328e-006</p></li>
</ul>
<p><strong>Model 4: ARMA(4,5)</strong></p>
<ul>
<li><p><strong>Observations:</strong> 1948:02-2020:03 (T = 866)</p></li>
<li><p><strong>Dependent Variable:</strong> d_UNRATE</p></li>
<li><p><strong>Standard Errors:</strong> Based on Hessian</p></li>
</ul>
<table class="table">
<colgroup>
<col style="width: 18%">
<col style="width: 15%">
<col style="width: 17%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Coefficient</th>
<th>Estimate</th>
<th>Std. Error</th>
<th>z-value</th>
<th>p-value</th>
<th>Significance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>const</td>
<td>0.002507</td>
<td>0.011390</td>
<td>0.2201</td>
<td>0.8258</td>
<td></td>
</tr>
<tr class="even">
<td>phi_1</td>
<td>0.578072</td>
<td>0.062491</td>
<td>9.250</td>
<td>&lt;0.0001</td>
<td>***</td>
</tr>
<tr class="odd">
<td>phi_2</td>
<td>0.117027</td>
<td>0.073948</td>
<td>1.583</td>
<td>0.1135</td>
<td></td>
</tr>
<tr class="even">
<td>phi_3</td>
<td>0.611279</td>
<td>0.108845</td>
<td>5.616</td>
<td>&lt;0.0001</td>
<td>***</td>
</tr>
<tr class="odd">
<td>phi_4</td>
<td>-0.695650</td>
<td>0.055781</td>
<td>-12.4700</td>
<td>&lt;0.0001</td>
<td>***</td>
</tr>
<tr class="even">
<td>theta_1</td>
<td>-0.585967</td>
<td>0.067105</td>
<td>-8.732</td>
<td>&lt;0.0001</td>
<td>***</td>
</tr>
<tr class="odd">
<td>theta_2</td>
<td>0.063179</td>
<td>0.074000</td>
<td>0.8538</td>
<td>0.3932</td>
<td></td>
</tr>
<tr class="even">
<td>theta_3</td>
<td>-0.595233</td>
<td>0.107839</td>
<td>-5.520</td>
<td>&lt;0.0001</td>
<td>***</td>
</tr>
<tr class="odd">
<td>theta_4</td>
<td>0.766918</td>
<td>0.069361</td>
<td>11.060</td>
<td>&lt;0.0001</td>
<td>***</td>
</tr>
<tr class="even">
<td>theta_5</td>
<td>0.030504</td>
<td>0.070963</td>
<td>0.4299</td>
<td>0.6673</td>
<td></td>
</tr>
</tbody>
</table>
<p><strong>Model Fit Statistics:</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>Statistic</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mean dependent var</td>
<td>0.001155</td>
</tr>
<tr class="even">
<td>S.D. dependent var</td>
<td>0.209924</td>
</tr>
<tr class="odd">
<td>Mean of innovations</td>
<td>-0.000422</td>
</tr>
<tr class="even">
<td>S.D. of innovations</td>
<td>0.192210</td>
</tr>
<tr class="odd">
<td>R-squared</td>
<td>0.160680</td>
</tr>
<tr class="even">
<td>Adjusted R-squared</td>
<td>0.152845</td>
</tr>
<tr class="odd">
<td>Log-likelihood</td>
<td>198.7941</td>
</tr>
<tr class="even">
<td>Akaike criterion</td>
<td>-375.5881</td>
</tr>
<tr class="odd">
<td>Schwarz criterion</td>
<td>-323.1854</td>
</tr>
<tr class="even">
<td>Hannan-Quinn</td>
<td>-355.5330</td>
</tr>
</tbody>
</table>
<p><strong>Roots of AR and MA Polynomials:</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>Type</th>
<th>Root</th>
<th>Real</th>
<th>Imaginary</th>
<th>Modulus</th>
<th>Frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>AR</td>
<td>Root 1</td>
<td>1.0508</td>
<td>0.4052</td>
<td>1.1262</td>
<td>0.0586</td>
</tr>
<tr class="even">
<td>AR</td>
<td>Root 2</td>
<td>1.0508</td>
<td>-0.4052</td>
<td>1.1262</td>
<td>-0.0586</td>
</tr>
<tr class="odd">
<td>AR</td>
<td>Root 3</td>
<td>-0.6114</td>
<td>-0.8715</td>
<td>1.0646</td>
<td>-0.3474</td>
</tr>
<tr class="even">
<td>AR</td>
<td>Root 4</td>
<td>-0.6114</td>
<td>0.8715</td>
<td>1.0646</td>
<td>0.3474</td>
</tr>
<tr class="odd">
<td>MA</td>
<td>Root 1</td>
<td>0.9450</td>
<td>0.5028</td>
<td>1.0704</td>
<td>0.0778</td>
</tr>
<tr class="even">
<td>MA</td>
<td>Root 2</td>
<td>0.9450</td>
<td>-0.5028</td>
<td>1.0704</td>
<td>-0.0778</td>
</tr>
</tbody>
</table>
<p><strong>Autocorrelation Test:</strong></p>
<p>Test for autocorrelation up to order 12:</p>
<ul>
<li><strong>Ljung-Box Q’</strong> = 41.5484</li>
<li><strong>p-value</strong> = P(Chi-square(10) &gt; 41.5484) = 1.741e-007</li>
</ul>
<p><strong>ARIMA Model Analysis Report</strong></p>
<p><strong>Metrics Overview:</strong></p>
<p>The following criteria are used to evaluate the goodness of fit for ARIMA models:</p>
<ol type="1">
<li><p><strong>Akaike Information Criterion (AIC):</strong> AIC measures the relative fit of a model while penalizing for the number of parameters. Lower values indicate a better model fit.</p></li>
<li><p><strong>Bayesian Information Criterion (BIC):</strong> Also known as the Schwarz criterion, BIC is similar to AIC but imposes a stricter penalty for additional parameters. It favors simpler models, with lower values indicating a better fit.</p></li>
<li><p><strong>Hannan-Quinn Information Criterion (HQIC):</strong> HQIC provides a balance between AIC and BIC in terms of penalizing model complexity. It offers a measure of fit with a focus on both model accuracy and simplicity.</p></li>
</ol>
<p>BIC and HQIC are more conservative compared to AIC, as they impose higher penalties for additional parameters. Thus, smaller values of these metrics suggest a better model fit, with a preference for models that are more parsimonious.</p>
<p><strong>Ljung-Box Q Statistic:</strong></p>
<p>The Ljung-Box Q test assesses autocorrelation in the residuals of a model.</p>
<ul>
<li><p><strong>Null Hypothesis (H0):</strong> There is no serial autocorrelation in the residuals.</p></li>
<li><p><strong>Alternative Hypothesis (Ha):</strong> There is serial autocorrelation in the residuals.</p></li>
</ul>
<p>A high p-value (greater than 0.05) suggests that the residuals are not significantly autocorrelated, indicating a good model fit. A low p-value indicates potential autocorrelation in the residuals, which suggests that the model may not fully capture the underlying data structure.</p>
<p><strong>ARIMA Model Comparison</strong></p>
<p>Below is a summary of the evaluated ARIMA models, including their adjusted R-squared, AIC, BIC, and Ljung-Box Q values:</p>
<table class="table">
<thead>
<tr class="header">
<th>Model</th>
<th>Adjusted R-squared</th>
<th>AIC</th>
<th>BIC</th>
<th>Ljung-Box Q</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>0.085465</td>
<td>-317.254</td>
<td>-298.199</td>
<td>75.3636</td>
</tr>
<tr class="even">
<td>2</td>
<td>0.121101</td>
<td>-350.557</td>
<td>-326.738</td>
<td>36.8101</td>
</tr>
<tr class="odd">
<td>3</td>
<td>0.134286</td>
<td>-362.107</td>
<td>-333.524</td>
<td>39.2977</td>
</tr>
<tr class="even">
<td>4</td>
<td>0.152845</td>
<td>-375.588</td>
<td>-323.185</td>
<td>17.9674</td>
</tr>
</tbody>
</table>
<p><strong>Best Model:</strong></p>
<p>Model 4 is identified as the best among the evaluated models. It has the highest adjusted R-squared (0.1528), the lowest AIC (-375.588), and the third lowest BIC (-323.185). Despite the Ljung-Box Q statistic indicating some residual autocorrelation, Model 4 performs best overall in terms of fit statistics.</p>
<p><strong>Residual Variance and Model Exploration</strong></p>
<p>The Ljung-Box test results suggest that some autocorrelation remains in the residuals of the models. The p-values for the Ljung-Box test are below 0.05, indicating that the residuals are not completely free of autocorrelation. This implies that additional variance might be captured by exploring further ARIMA models or adjusting model parameters to improve fit and reduce residual autocorrelation.</p>
</section>
<section id="sas-code-arima-models" class="level1">
<h1>SAS Code: ARIMA MODELS</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># LIBNAME mylib "P:\";</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co"># FILENAME bigrec "P:\fa15_data.txt" LRECL = 65576;</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co"># DATA mytemp;</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co"># INFILE bigrec;</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co"># INPUT</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="co"># myid 1-7</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="co"># purchase_online_safe_aglo 5526</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="co"># purchase_online_safe_agli 5564</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="co"># purchase_online_safe_neit 5640</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="co"># purchase_online_safe_dgli 5678</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="co"># purchase_online_safe_dglo 5716</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a><span class="co"># buy_online_aglo 5518</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a><span class="co"># buy_online_agli 5556</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a><span class="co"># buy_online_neit 5632</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a><span class="co"># buy_online_dgli 5670</span></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a><span class="co"># buy_online_dglo 5708</span></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a><span class="co"># use_devices_for_deal_aglo 5508</span></span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a><span class="co"># use_devices_for_deal_agli 5546</span></span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a><span class="co"># use_devices_for_deal_neit 5622</span></span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a><span class="co"># use_devices_for_deal_dgli 5660</span></span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a><span class="co"># use_devices_for_deal_dglo 5698</span></span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a><span class="co"># hear_products_email_aglo 5525</span></span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a><span class="co"># hear_products_email_agli 5563</span></span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a><span class="co"># hear_products_email_neit 5639</span></span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a><span class="co"># hear_products_email_dgli 5677</span></span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a><span class="co"># hear_products_email_dglo 5715</span></span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a><span class="co"># internet_chnge_shop_aglo 5495</span></span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a><span class="co"># internet_chnge_shop_agli 5533</span></span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a><span class="co"># internet_chnge_shop_neit 5609</span></span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a><span class="co"># internet_chnge_shop_dgli 5647</span></span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a><span class="co"># internet_chnge_shop_dglo 5685</span></span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a><span class="co"># environ_friendly_aglo 4181</span></span>
<span id="cb9-38"><a href="#cb9-38" aria-hidden="true" tabindex="-1"></a><span class="co"># environ_friendly_agli 4195</span></span>
<span id="cb9-39"><a href="#cb9-39" aria-hidden="true" tabindex="-1"></a><span class="co"># environ_friendly_neit 4223</span></span>
<span id="cb9-40"><a href="#cb9-40" aria-hidden="true" tabindex="-1"></a><span class="co"># environ_friendly_dgli 4237</span></span>
<span id="cb9-41"><a href="#cb9-41" aria-hidden="true" tabindex="-1"></a><span class="co"># environ_friendly_dglo 4251</span></span>
<span id="cb9-42"><a href="#cb9-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-43"><a href="#cb9-43" aria-hidden="true" tabindex="-1"></a><span class="co"># recycle_prods_aglo 4190</span></span>
<span id="cb9-44"><a href="#cb9-44" aria-hidden="true" tabindex="-1"></a><span class="co"># recycle_prods_agli 4204</span></span>
<span id="cb9-45"><a href="#cb9-45" aria-hidden="true" tabindex="-1"></a><span class="co"># recycle_prods_neit 4232</span></span>
<span id="cb9-46"><a href="#cb9-46" aria-hidden="true" tabindex="-1"></a><span class="co"># recycle_prods_dgli 4246</span></span>
<span id="cb9-47"><a href="#cb9-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-48"><a href="#cb9-48" aria-hidden="true" tabindex="-1"></a><span class="co"># recycle_prods_dglo 4260</span></span>
<span id="cb9-49"><a href="#cb9-49" aria-hidden="true" tabindex="-1"></a><span class="co"># environ_good_business_aglo 4182</span></span>
<span id="cb9-50"><a href="#cb9-50" aria-hidden="true" tabindex="-1"></a><span class="co"># environ_good_business_agli 4196</span></span>
<span id="cb9-51"><a href="#cb9-51" aria-hidden="true" tabindex="-1"></a><span class="co"># environ_good_business_neit 4224</span></span>
<span id="cb9-52"><a href="#cb9-52" aria-hidden="true" tabindex="-1"></a><span class="co"># environ_good_business_dgli 4238</span></span>
<span id="cb9-53"><a href="#cb9-53" aria-hidden="true" tabindex="-1"></a><span class="co"># environ_good_business_dglo 4252</span></span>
<span id="cb9-54"><a href="#cb9-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-55"><a href="#cb9-55" aria-hidden="true" tabindex="-1"></a><span class="co"># environ_personal_ob_aglo 4184</span></span>
<span id="cb9-56"><a href="#cb9-56" aria-hidden="true" tabindex="-1"></a><span class="co"># environ_personal_ob_agli 4198</span></span>
<span id="cb9-57"><a href="#cb9-57" aria-hidden="true" tabindex="-1"></a><span class="co"># environ_personal_ob_neit 4226</span></span>
<span id="cb9-58"><a href="#cb9-58" aria-hidden="true" tabindex="-1"></a><span class="co"># environ_personal_ob_dgli 4240</span></span>
<span id="cb9-59"><a href="#cb9-59" aria-hidden="true" tabindex="-1"></a><span class="co"># environ_personal_ob_dglo 4254</span></span>
<span id="cb9-60"><a href="#cb9-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-61"><a href="#cb9-61" aria-hidden="true" tabindex="-1"></a><span class="co"># comp_help_cons_env_aglo 4183</span></span>
<span id="cb9-62"><a href="#cb9-62" aria-hidden="true" tabindex="-1"></a><span class="co"># comp_help_cons_env_agli 4197</span></span>
<span id="cb9-63"><a href="#cb9-63" aria-hidden="true" tabindex="-1"></a><span class="co"># comp_help_cons_env_neit 4225</span></span>
<span id="cb9-64"><a href="#cb9-64" aria-hidden="true" tabindex="-1"></a><span class="co"># comp_help_cons_env_dgli 4239</span></span>
<span id="cb9-65"><a href="#cb9-65" aria-hidden="true" tabindex="-1"></a><span class="co"># comp_help_cons_env_dglo 4253</span></span>
<span id="cb9-66"><a href="#cb9-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-67"><a href="#cb9-67" aria-hidden="true" tabindex="-1"></a><span class="co"># adidas_brand 42607;</span></span>
<span id="cb9-68"><a href="#cb9-68" aria-hidden="true" tabindex="-1"></a><span class="co"># RUN;</span></span>
<span id="cb9-69"><a href="#cb9-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-70"><a href="#cb9-70" aria-hidden="true" tabindex="-1"></a><span class="co"># \* the above reads in the raw data from the data file - now create five point scale variables \*/</span></span>
<span id="cb9-71"><a href="#cb9-71" aria-hidden="true" tabindex="-1"></a><span class="co"># \* now before we create variables lets create formats so we know what each value will mean \*/</span></span>
<span id="cb9-72"><a href="#cb9-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-73"><a href="#cb9-73" aria-hidden="true" tabindex="-1"></a><span class="co"># PROC FORMAT;</span></span>
<span id="cb9-74"><a href="#cb9-74" aria-hidden="true" tabindex="-1"></a><span class="co"># VALUE myscale</span></span>
<span id="cb9-75"><a href="#cb9-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-76"><a href="#cb9-76" aria-hidden="true" tabindex="-1"></a><span class="co">#   1 = "disagree a lot"</span></span>
<span id="cb9-77"><a href="#cb9-77" aria-hidden="true" tabindex="-1"></a><span class="co">#   2 = "disagree a little"</span></span>
<span id="cb9-78"><a href="#cb9-78" aria-hidden="true" tabindex="-1"></a><span class="co">#   3 = "neither agree nor disagree"</span></span>
<span id="cb9-79"><a href="#cb9-79" aria-hidden="true" tabindex="-1"></a><span class="co">#   4 = "agree a little"</span></span>
<span id="cb9-80"><a href="#cb9-80" aria-hidden="true" tabindex="-1"></a><span class="co">#   5 = "agree a lot";</span></span>
<span id="cb9-81"><a href="#cb9-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-82"><a href="#cb9-82" aria-hidden="true" tabindex="-1"></a><span class="co"># VALUE yesno</span></span>
<span id="cb9-83"><a href="#cb9-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-84"><a href="#cb9-84" aria-hidden="true" tabindex="-1"></a><span class="co">#   0 = "no"</span></span>
<span id="cb9-85"><a href="#cb9-85" aria-hidden="true" tabindex="-1"></a><span class="co">#   1 = "yes";</span></span>
<span id="cb9-86"><a href="#cb9-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-87"><a href="#cb9-87" aria-hidden="true" tabindex="-1"></a><span class="co"># RUN;</span></span>
<span id="cb9-88"><a href="#cb9-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-89"><a href="#cb9-89" aria-hidden="true" tabindex="-1"></a><span class="co"># \* do that by creating a new temp sas data set myvars by starting with the temp sas data set mytemp \*/</span></span>
<span id="cb9-90"><a href="#cb9-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-91"><a href="#cb9-91" aria-hidden="true" tabindex="-1"></a><span class="co"># DATA myvars;</span></span>
<span id="cb9-92"><a href="#cb9-92" aria-hidden="true" tabindex="-1"></a><span class="co"># SET mytemp;</span></span>
<span id="cb9-93"><a href="#cb9-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-94"><a href="#cb9-94" aria-hidden="true" tabindex="-1"></a><span class="co"># IF purchase_online_safe_dglo = 1 THEN purchase_online_safe = 1;</span></span>
<span id="cb9-95"><a href="#cb9-95" aria-hidden="true" tabindex="-1"></a><span class="co"># IF purchase_online_safe_dgli = 1 THEN purchase_online_safe = 2;</span></span>
<span id="cb9-96"><a href="#cb9-96" aria-hidden="true" tabindex="-1"></a><span class="co"># IF purchase_online_safe_neit = 1 THEN purchase_online_safe = 3;</span></span>
<span id="cb9-97"><a href="#cb9-97" aria-hidden="true" tabindex="-1"></a><span class="co"># IF purchase_online_safe_agli = 1 THEN purchase_online_safe = 4;</span></span>
<span id="cb9-98"><a href="#cb9-98" aria-hidden="true" tabindex="-1"></a><span class="co"># IF purchase_online_safe_aglo = 1 THEN purchase_online_safe = 5;</span></span>
<span id="cb9-99"><a href="#cb9-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-100"><a href="#cb9-100" aria-hidden="true" tabindex="-1"></a><span class="co"># IF buy_online_dglo = 1 THEN buy_online = 1;</span></span>
<span id="cb9-101"><a href="#cb9-101" aria-hidden="true" tabindex="-1"></a><span class="co"># IF buy_online_dgli = 1 THEN buy_online = 2;</span></span>
<span id="cb9-102"><a href="#cb9-102" aria-hidden="true" tabindex="-1"></a><span class="co"># IF buy_online_neit = 1 THEN buy_online = 3;</span></span>
<span id="cb9-103"><a href="#cb9-103" aria-hidden="true" tabindex="-1"></a><span class="co"># IF buy_online_agli = 1 THEN buy_online = 4;</span></span>
<span id="cb9-104"><a href="#cb9-104" aria-hidden="true" tabindex="-1"></a><span class="co"># IF buy_online_aglo = 1 THEN buy_online = 5;</span></span>
<span id="cb9-105"><a href="#cb9-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-106"><a href="#cb9-106" aria-hidden="true" tabindex="-1"></a><span class="co"># IF use_devices_for_deal_dglo = 1 THEN use_devices_for_deal = 1;</span></span>
<span id="cb9-107"><a href="#cb9-107" aria-hidden="true" tabindex="-1"></a><span class="co"># IF use_devices_for_deal_dgli = 1 THEN use_devices_for_deal = 2;</span></span>
<span id="cb9-108"><a href="#cb9-108" aria-hidden="true" tabindex="-1"></a><span class="co"># IF use_devices_for_deal_neit = 1 THEN use_devices_for_deal = 3;</span></span>
<span id="cb9-109"><a href="#cb9-109" aria-hidden="true" tabindex="-1"></a><span class="co"># IF use_devices_for_deal_agli = 1 THEN use_devices_for_deal = 4;</span></span>
<span id="cb9-110"><a href="#cb9-110" aria-hidden="true" tabindex="-1"></a><span class="co"># IF use_devices_for_deal_aglo = 1 THEN use_devices_for_deal = 5;</span></span>
<span id="cb9-111"><a href="#cb9-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-112"><a href="#cb9-112" aria-hidden="true" tabindex="-1"></a><span class="co"># IF hear_products_email_dglo = 1 THEN hear_products_email = 1;</span></span>
<span id="cb9-113"><a href="#cb9-113" aria-hidden="true" tabindex="-1"></a><span class="co"># IF hear_products_email_dgli = 1 THEN hear_products_email = 2;</span></span>
<span id="cb9-114"><a href="#cb9-114" aria-hidden="true" tabindex="-1"></a><span class="co"># IF hear_products_email_neit = 1 THEN hear_products_email = 3;</span></span>
<span id="cb9-115"><a href="#cb9-115" aria-hidden="true" tabindex="-1"></a><span class="co"># IF hear_products_email_agli = 1 THEN hear_products_email = 4;</span></span>
<span id="cb9-116"><a href="#cb9-116" aria-hidden="true" tabindex="-1"></a><span class="co"># IF hear_products_email_aglo = 1 THEN hear_products_email = 5;</span></span>
<span id="cb9-117"><a href="#cb9-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-118"><a href="#cb9-118" aria-hidden="true" tabindex="-1"></a><span class="co"># IF internet_chnge_shop_dglo = 1 THEN internet_chnge_shop = 1;</span></span>
<span id="cb9-119"><a href="#cb9-119" aria-hidden="true" tabindex="-1"></a><span class="co"># IF internet_chnge_shop_dgli = 1 THEN internet_chnge_shop = 2;</span></span>
<span id="cb9-120"><a href="#cb9-120" aria-hidden="true" tabindex="-1"></a><span class="co"># IF internet_chnge_shop_neit = 1 THEN internet_chnge_shop = 3;</span></span>
<span id="cb9-121"><a href="#cb9-121" aria-hidden="true" tabindex="-1"></a><span class="co"># IF internet_chnge_shop_agli = 1 THEN internet_chnge_shop = 4;</span></span>
<span id="cb9-122"><a href="#cb9-122" aria-hidden="true" tabindex="-1"></a><span class="co"># IF internet_chnge_shop_aglo = 1 THEN internet_chnge_shop = 5;</span></span>
<span id="cb9-123"><a href="#cb9-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-124"><a href="#cb9-124" aria-hidden="true" tabindex="-1"></a><span class="co"># IF environ_friendly_dglo = 1 THEN environ_friendly = 1;</span></span>
<span id="cb9-125"><a href="#cb9-125" aria-hidden="true" tabindex="-1"></a><span class="co"># IF environ_friendly_dgli = 1 THEN environ_friendly = 2;</span></span>
<span id="cb9-126"><a href="#cb9-126" aria-hidden="true" tabindex="-1"></a><span class="co"># IF environ_friendly_neit = 1 THEN environ_friendly = 3;</span></span>
<span id="cb9-127"><a href="#cb9-127" aria-hidden="true" tabindex="-1"></a><span class="co"># IF environ_friendly_agli = 1 THEN environ_friendly = 4;</span></span>
<span id="cb9-128"><a href="#cb9-128" aria-hidden="true" tabindex="-1"></a><span class="co"># IF environ_friendly_aglo = 1 THEN environ_friendly = 5;</span></span>
<span id="cb9-129"><a href="#cb9-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-130"><a href="#cb9-130" aria-hidden="true" tabindex="-1"></a><span class="co"># IF recycle_prods_dglo = 1 THEN recycle_prods = 1;</span></span>
<span id="cb9-131"><a href="#cb9-131" aria-hidden="true" tabindex="-1"></a><span class="co"># IF recycle_prods_dgli = 1 THEN recycle_prods = 2;</span></span>
<span id="cb9-132"><a href="#cb9-132" aria-hidden="true" tabindex="-1"></a><span class="co"># IF recycle_prods_neit = 1 THEN recycle_prods = 3;</span></span>
<span id="cb9-133"><a href="#cb9-133" aria-hidden="true" tabindex="-1"></a><span class="co"># IF recycle_prods_agli = 1 THEN recycle_prods = 4;</span></span>
<span id="cb9-134"><a href="#cb9-134" aria-hidden="true" tabindex="-1"></a><span class="co"># IF recycle_prods_aglo = 1 THEN recycle_prods = 5;</span></span>
<span id="cb9-135"><a href="#cb9-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-136"><a href="#cb9-136" aria-hidden="true" tabindex="-1"></a><span class="co"># IF environ_good_business_dglo = 1 THEN environ_good_business = 1;</span></span>
<span id="cb9-137"><a href="#cb9-137" aria-hidden="true" tabindex="-1"></a><span class="co"># IF environ_good_business_dgli = 1 THEN environ_good_business = 2;</span></span>
<span id="cb9-138"><a href="#cb9-138" aria-hidden="true" tabindex="-1"></a><span class="co"># IF environ_good_business_neit = 1 THEN environ_good_business = 3;</span></span>
<span id="cb9-139"><a href="#cb9-139" aria-hidden="true" tabindex="-1"></a><span class="co"># IF environ_good_business_agli = 1 THEN environ_good_business = 4;</span></span>
<span id="cb9-140"><a href="#cb9-140" aria-hidden="true" tabindex="-1"></a><span class="co"># IF environ_good_business_aglo = 1 THEN environ_good_business = 5;</span></span>
<span id="cb9-141"><a href="#cb9-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-142"><a href="#cb9-142" aria-hidden="true" tabindex="-1"></a><span class="co"># IF environ_personal_ob_dglo = 1 THEN environ_personal_ob = 1;</span></span>
<span id="cb9-143"><a href="#cb9-143" aria-hidden="true" tabindex="-1"></a><span class="co"># IF environ_personal_ob_dgli = 1 THEN environ_personal_ob = 2;</span></span>
<span id="cb9-144"><a href="#cb9-144" aria-hidden="true" tabindex="-1"></a><span class="co"># IF environ_personal_ob_neit = 1 THEN environ_personal_ob = 3;</span></span>
<span id="cb9-145"><a href="#cb9-145" aria-hidden="true" tabindex="-1"></a><span class="co"># IF environ_personal_ob_agli = 1 THEN environ_personal_ob = 4;</span></span>
<span id="cb9-146"><a href="#cb9-146" aria-hidden="true" tabindex="-1"></a><span class="co"># IF environ_personal_ob_aglo = 1 THEN environ_personal_ob = 5;</span></span>
<span id="cb9-147"><a href="#cb9-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-148"><a href="#cb9-148" aria-hidden="true" tabindex="-1"></a><span class="co"># IF comp_help_cons_env_dglo = 1 THEN comp_help_cons_env = 1;</span></span>
<span id="cb9-149"><a href="#cb9-149" aria-hidden="true" tabindex="-1"></a><span class="co"># IF comp_help_cons_env_dgli = 1 THEN comp_help_cons_env = 2;</span></span>
<span id="cb9-150"><a href="#cb9-150" aria-hidden="true" tabindex="-1"></a><span class="co"># IF comp_help_cons_env_neit = 1 THEN comp_help_cons_env = 3;</span></span>
<span id="cb9-151"><a href="#cb9-151" aria-hidden="true" tabindex="-1"></a><span class="co"># IF comp_help_cons_env_agli = 1 THEN comp_help_cons_env = 4;</span></span>
<span id="cb9-152"><a href="#cb9-152" aria-hidden="true" tabindex="-1"></a><span class="co"># IF comp_help_cons_env_aglo = 1 THEN comp_help_cons_env = 5;</span></span>
<span id="cb9-153"><a href="#cb9-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-154"><a href="#cb9-154" aria-hidden="true" tabindex="-1"></a><span class="co"># IF adidas_brand = . THEN adidas = 0;</span></span>
<span id="cb9-155"><a href="#cb9-155" aria-hidden="true" tabindex="-1"></a><span class="co"># IF adidas_brand = 1 THEN adidas = 1;</span></span>
<span id="cb9-156"><a href="#cb9-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-157"><a href="#cb9-157" aria-hidden="true" tabindex="-1"></a><span class="co"># FORMAT purchase_online_safe buy_online use_devices_for_deal hear_products_email internet_chnge_shop environ_friendly recycle_prods environ_good_business environ_personal_ob comp_help_cons_env myscale.</span></span>
<span id="cb9-158"><a href="#cb9-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-159"><a href="#cb9-159" aria-hidden="true" tabindex="-1"></a><span class="co">#   adidas yesno. ;</span></span>
<span id="cb9-160"><a href="#cb9-160" aria-hidden="true" tabindex="-1"></a><span class="co"># RUN;</span></span>
<span id="cb9-161"><a href="#cb9-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-162"><a href="#cb9-162" aria-hidden="true" tabindex="-1"></a><span class="co"># PROC FACTOR DATA = myvars</span></span>
<span id="cb9-163"><a href="#cb9-163" aria-hidden="true" tabindex="-1"></a><span class="co"># MAXITER=100</span></span>
<span id="cb9-164"><a href="#cb9-164" aria-hidden="true" tabindex="-1"></a><span class="co"># METHOD=principal</span></span>
<span id="cb9-165"><a href="#cb9-165" aria-hidden="true" tabindex="-1"></a><span class="co"># MINEIGEN=1</span></span>
<span id="cb9-166"><a href="#cb9-166" aria-hidden="true" tabindex="-1"></a><span class="co"># ROTATE=varimax</span></span>
<span id="cb9-167"><a href="#cb9-167" aria-hidden="true" tabindex="-1"></a><span class="co"># MSA</span></span>
<span id="cb9-168"><a href="#cb9-168" aria-hidden="true" tabindex="-1"></a><span class="co"># SCREE</span></span>
<span id="cb9-169"><a href="#cb9-169" aria-hidden="true" tabindex="-1"></a><span class="co"># SCORE</span></span>
<span id="cb9-170"><a href="#cb9-170" aria-hidden="true" tabindex="-1"></a><span class="co"># PRINT</span></span>
<span id="cb9-171"><a href="#cb9-171" aria-hidden="true" tabindex="-1"></a><span class="co"># NFACTORS=2</span></span>
<span id="cb9-172"><a href="#cb9-172" aria-hidden="true" tabindex="-1"></a><span class="co"># OUT=myscores;</span></span>
<span id="cb9-173"><a href="#cb9-173" aria-hidden="true" tabindex="-1"></a><span class="co"># VAR purchase_online_safe</span></span>
<span id="cb9-174"><a href="#cb9-174" aria-hidden="true" tabindex="-1"></a><span class="co"># buy_online</span></span>
<span id="cb9-175"><a href="#cb9-175" aria-hidden="true" tabindex="-1"></a><span class="co"># use_devices_for_deal</span></span>
<span id="cb9-176"><a href="#cb9-176" aria-hidden="true" tabindex="-1"></a><span class="co"># hear_products_email</span></span>
<span id="cb9-177"><a href="#cb9-177" aria-hidden="true" tabindex="-1"></a><span class="co"># internet_chnge_shop</span></span>
<span id="cb9-178"><a href="#cb9-178" aria-hidden="true" tabindex="-1"></a><span class="co"># environ_friendly</span></span>
<span id="cb9-179"><a href="#cb9-179" aria-hidden="true" tabindex="-1"></a><span class="co"># recycle_prods</span></span>
<span id="cb9-180"><a href="#cb9-180" aria-hidden="true" tabindex="-1"></a><span class="co"># environ_good_business</span></span>
<span id="cb9-181"><a href="#cb9-181" aria-hidden="true" tabindex="-1"></a><span class="co"># environ_personal_ob</span></span>
<span id="cb9-182"><a href="#cb9-182" aria-hidden="true" tabindex="-1"></a><span class="co"># comp_help_cons_env;</span></span>
<span id="cb9-183"><a href="#cb9-183" aria-hidden="true" tabindex="-1"></a><span class="co"># RUN;</span></span>
<span id="cb9-184"><a href="#cb9-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-185"><a href="#cb9-185" aria-hidden="true" tabindex="-1"></a><span class="co"># DATA myscores1;</span></span>
<span id="cb9-186"><a href="#cb9-186" aria-hidden="true" tabindex="-1"></a><span class="co"># SET myscores;</span></span>
<span id="cb9-187"><a href="#cb9-187" aria-hidden="true" tabindex="-1"></a><span class="co"># RENAME factor1 = onlineshopper;</span></span>
<span id="cb9-188"><a href="#cb9-188" aria-hidden="true" tabindex="-1"></a><span class="co"># RENAME factor2 = environconscious;</span></span>
<span id="cb9-189"><a href="#cb9-189" aria-hidden="true" tabindex="-1"></a><span class="co"># RENAME my_id = resp_id;</span></span>
<span id="cb9-190"><a href="#cb9-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-191"><a href="#cb9-191" aria-hidden="true" tabindex="-1"></a><span class="co"># RUN;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="basic-statistics-levels-of-measurement-and-statistical-techniques" class="level1">
<h1>Basic Statistics: Levels of Measurement, and Statistical Techniques</h1>
<p><strong>Dependent Variable</strong>: A variable that depends on the changes made to the independent variable.</p>
<p><strong>Independent Variable</strong>: The variable that you manipulate or control to observe its effect on the dependent variable.</p>
<p><strong>Control Variable</strong>: A variable that may affect the dependent variable but is not of primary interest in the study.</p>
<p><strong>Levels of Measurement</strong></p>
<ol type="1">
<li>Nominal: Categorical data with distinct groups, without any order or ranking.</li>
</ol>
<ul>
<li>Example: Eye color (brown, black, blue).</li>
</ul>
<ol start="2" type="1">
<li>Ordinal: Categorical data that can be ordered or ranked.</li>
</ol>
<ul>
<li>Example: Education levels (high school diploma, bachelor’s, master’s, Ph.D.).</li>
</ul>
<ol start="3" type="1">
<li>Interval: Data with equal intervals between values, but no true zero. Example: Temperature in Celsius. Ratio: Data with equal intervals and an absolute zero point.</li>
</ol>
<ul>
<li>Example: Height.</li>
</ul>
<p><strong>Criteria for Choosing Statistical Techniques</strong></p>
<p>According to the <a href="https://stats.oarc.ucla.edu/other/mult-pkg/whatstat/"><strong>IDRE Chart</strong></a>, two important criteria for selecting a statistical technique are:</p>
<ul>
<li>The levels of measurement of both the dependent and independent variables.</li>
<li>The number of dependent and independent variables.</li>
</ul>
<p>Additionally, the nature of the research question plays a crucial role in determining the appropriate technique.</p>
<p><strong>Descriptive vs.&nbsp;Inferential Statistics</strong></p>
<ul>
<li>Descriptive Statistics: Summarize and present the main features of the data.</li>
<li>Inferential Statistics: Make predictions and draw conclusions based on the data.</li>
</ul>
<p><strong>Assumptions in Statistical Tests</strong></p>
<ul>
<li>Benefit: Proper assumptions ensure reliable and trustworthy results.</li>
<li>Cost: Violating assumptions can compromise the validity and credibility of the test.</li>
</ul>
<p><strong>Impact of Violating Assumptions</strong></p>
<p>Violating the assumptions of a statistical test can undermine the integrity of the analysis, leading to questionable results and a loss of credibility.</p>
<p><strong>Selecting Appropriate Statistical Tests</strong></p>
<ol type="1">
<li>Colored Contact Lenses and Gender:</li>
</ol>
<ul>
<li>Variables: Color of lenses (independent), gender (dependent).</li>
<li>Test: Chi-square test (both variables are nominal).</li>
</ul>
<ol start="2" type="1">
<li>Art Auction Prices by Gender:</li>
</ol>
<ul>
<li>Variables: Gender (independent), price paid for art (dependent).</li>
<li>Test: t-test (price is continuous).</li>
</ul>
<ol start="3" type="1">
<li>Vegematic Sales by Product and Demographics:</li>
</ol>
<ul>
<li>Variables: Product color, price, region, gender, household income (independent), number of products sold (dependent).</li>
<li>Test: ANOVA.</li>
</ul>
<ol start="4" type="1">
<li>Magazine Pages and Sales:</li>
</ol>
<ul>
<li>Variables: Number of pages (independent), copies sold (dependent).</li>
<li>Test: Pearson correlation.</li>
</ul>
<ol start="5" type="1">
<li>Hair Growth in Cats by Drug, Gender, and Coat Color:</li>
</ol>
<ul>
<li>Variables: Drug, cat gender, coat color (independent), hair growth (dependent).</li>
<li>Test: Three-way ANOVA.</li>
</ul>
<p>Other Key Statical Concepts:</p>
<p><strong>Population and Sample</strong></p>
<ul>
<li>Population: The entire set or group being studied.</li>
<li>Sample: A subset of the population used for the study.</li>
<li>Inferential Statistics: The goal is to make predictions about the population based on the sample.</li>
</ul>
<p><strong>Measures of Central Tendency</strong></p>
<ul>
<li><p>Mean: The average of all data points.</p></li>
<li><p>Median: The middle value when data is arranged in order.</p></li>
<li><p>Example: In an exam, the mean tells you the overall class performance, while the median can indicate the typical student’s performance.</p></li>
</ul>
<p><strong>Variance and Standard Deviation</strong></p>
<ul>
<li><p>Variance: Measures how much data points deviate from the mean.</p></li>
<li><p>Standard Deviation: The square root of the variance, indicating the spread of data around the mean.</p></li>
</ul>
<p>When data points are tightly packed around the mean, variance and standard deviation are lower.</p>
<p><strong>Confidence Intervals</strong></p>
<ul>
<li>Confidence Interval: Represents the range in which a population parameter is expected to fall a certain percentage of the time.</li>
<li>For example, in a survey of 150 voters where 45% support a candidate, a 95% confidence interval around this proportion ranges from ~0.3704 to 0.5296.</li>
</ul>
<p><strong>Z-Scores</strong></p>
<ul>
<li>Z-Score: Measures how many standard deviations a data point is from the mean.</li>
<li>Example: For UTSA student ages with a mean of 26 and a standard deviation of 4, the Z-score for a student aged 24 is calculated as:</li>
</ul>
<p><span class="math display">\[ Z = \frac{24 - 26}{4} = -0.5 \]</span></p>
</section>
<section id="section" class="level1">
<h1></h1>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>